import type { Category, ContentCard } from "./types";

// Données de démonstration : affichées uniquement quand Supabase
// n'est pas encore configuré (pour prévisualiser l'interface).

export const demoCategories: Category[] = [
  { id: "c1", name: "Développement", slug: "developpement", description: "Code, web et applications." },
  { id: "c2", name: "Entrepreneuriat", slug: "entrepreneuriat", description: "Créer et faire grandir son activité." },
  { id: "c3", name: "Marketing digital", slug: "marketing-digital", description: "Réseaux sociaux, SEO, publicité." },
  { id: "c4", name: "Langues", slug: "langues", description: "Wolof, français, anglais et plus." },
  { id: "c5", name: "Design", slug: "design", description: "UI/UX, graphisme, création visuelle." },
];

const now = new Date().toISOString();

export const demoContents: ContentCard[] = [
  {
    id: "1",
    author_id: "",
    author_name: "Awa Diop",
    category_id: "c1",
    category_name: "Développement",
    title: "Débuter avec Next.js et Supabase",
    slug: "debuter-nextjs-supabase",
    description:
      "Un guide pratique en français pour créer votre première application web moderne avec Next.js et une base de données Supabase.",
    type: "ebook",
    price: 5000,
    cover_url: "/covers/cover-nextjs.jpg",
    file_url: null,
    status: "publie",
    rejection_reason: null,
    created_at: now,
    updated_at: now,
    published_at: now,
  },
  {
    id: "2",
    author_id: "",
    author_name: "Moussa Ndiaye",
    category_id: "c2",
    category_name: "Entrepreneuriat",
    title: "Lancer son business au Sénégal",
    slug: "lancer-business-senegal",
    description:
      "Les étapes concrètes pour créer une entreprise au Sénégal : statuts, financement, premiers clients.",
    type: "cours",
    price: 15000,
    cover_url: "/covers/cover-business.jpg",
    file_url: null,
    status: "publie",
    rejection_reason: null,
    created_at: now,
    updated_at: now,
    published_at: now,
  },
  {
    id: "3",
    author_id: "",
    author_name: "Fatou Sarr",
    category_id: "c3",
    category_name: "Marketing digital",
    title: "Maîtriser les réseaux sociaux",
    slug: "maitriser-reseaux-sociaux",
    description:
      "Stratégie de contenu, community management et publicité pour développer votre visibilité en Afrique de l'Ouest.",
    type: "video",
    price: 12000,
    cover_url: "/covers/cover-social.jpg",
    file_url: null,
    status: "publie",
    rejection_reason: null,
    created_at: now,
    updated_at: now,
    published_at: now,
  },
  {
    id: "4",
    author_id: "",
    author_name: "Ibrahima Fall",
    category_id: "c4",
    category_name: "Langues",
    title: "Apprendre le wolof — niveau débutant",
    slug: "apprendre-wolof-debutant",
    description:
      "Les bases du wolof pour communiquer au quotidien : salutations, vocabulaire essentiel, expressions courantes.",
    type: "audio",
    price: 7500,
    cover_url: "/covers/cover-wolof.jpg",
    file_url: null,
    status: "publie",
    rejection_reason: null,
    created_at: now,
    updated_at: now,
    published_at: now,
  },
  {
    id: "5",
    author_id: "",
    author_name: "Aminata Ba",
    category_id: "c5",
    category_name: "Design",
    title: "Modèles de CV et lettres de motivation",
    slug: "modeles-cv-lettres",
    description:
      "10 modèles prêts à l'emploi (Word + Canva) pour des candidatures professionnelles et modernes.",
    type: "document",
    price: 3000,
    cover_url: "/covers/cover-cv.jpg",
    file_url: null,
    status: "publie",
    rejection_reason: null,
    created_at: now,
    updated_at: now,
    published_at: now,
  },
  {
    id: "6",
    author_id: "",
    author_name: "Cheikh Gueye",
    category_id: "c2",
    category_name: "Entrepreneuriat",
    title: "Gérer sa trésorerie au quotidien",
    slug: "gerer-tresorerie",
    description:
      "Des méthodes simples pour suivre vos entrées et sorties d'argent et éviter les mauvaises surprises.",
    type: "ebook",
    price: 4500,
    cover_url: "/covers/cover-finance.jpg",
    file_url: null,
    status: "publie",
    rejection_reason: null,
    created_at: now,
    updated_at: now,
    published_at: now,
  },
];
